// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/figment-networks/oasishub-indexer/usecase/validator (interfaces: DecorateStore)

// Package mock_validator is a generated GoMock package.
package mock_validator

import (
	model "github.com/figment-networks/oasishub-indexer/model"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockDecorateStore is a mock of DecorateStore interface
type MockDecorateStore struct {
	ctrl     *gomock.Controller
	recorder *MockDecorateStoreMockRecorder
}

// MockDecorateStoreMockRecorder is the mock recorder for MockDecorateStore
type MockDecorateStoreMockRecorder struct {
	mock *MockDecorateStore
}

// NewMockDecorateStore creates a new mock instance
func NewMockDecorateStore(ctrl *gomock.Controller) *MockDecorateStore {
	mock := &MockDecorateStore{ctrl: ctrl}
	mock.recorder = &MockDecorateStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockDecorateStore) EXPECT() *MockDecorateStoreMockRecorder {
	return m.recorder
}

// CreateOrUpdate mocks base method
func (m *MockDecorateStore) CreateOrUpdate(arg0 *model.ValidatorAgg) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrUpdate", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrUpdate indicates an expected call of CreateOrUpdate
func (mr *MockDecorateStoreMockRecorder) CreateOrUpdate(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrUpdate", reflect.TypeOf((*MockDecorateStore)(nil).CreateOrUpdate), arg0)
}

// FindByAddress mocks base method
func (m *MockDecorateStore) FindByAddress(arg0 string) (*model.ValidatorAgg, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByAddress", arg0)
	ret0, _ := ret[0].(*model.ValidatorAgg)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByAddress indicates an expected call of FindByAddress
func (mr *MockDecorateStoreMockRecorder) FindByAddress(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByAddress", reflect.TypeOf((*MockDecorateStore)(nil).FindByAddress), arg0)
}
