// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/figment-networks/oasishub-indexer/repos/delegationseqrepo (interfaces: DbRepo)

// Package mock_delegationseqrepo is a generated GoMock package.
package mock_delegationseqrepo

import (
	delegationseq "github.com/figment-networks/oasishub-indexer/models/delegationseq"
	types "github.com/figment-networks/oasishub-indexer/types"
	errors "github.com/figment-networks/oasishub-indexer/utils/errors"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockDbRepo is a mock of DbRepo interface
type MockDbRepo struct {
	ctrl     *gomock.Controller
	recorder *MockDbRepoMockRecorder
}

// MockDbRepoMockRecorder is the mock recorder for MockDbRepo
type MockDbRepoMockRecorder struct {
	mock *MockDbRepo
}

// NewMockDbRepo creates a new mock instance
func NewMockDbRepo(ctrl *gomock.Controller) *MockDbRepo {
	mock := &MockDbRepo{ctrl: ctrl}
	mock.recorder = &MockDbRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockDbRepo) EXPECT() *MockDbRepoMockRecorder {
	return m.recorder
}

// Create mocks base method
func (m *MockDbRepo) Create(arg0 *delegationseq.Model) errors.ApplicationError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(errors.ApplicationError)
	return ret0
}

// Create indicates an expected call of Create
func (mr *MockDbRepoMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDbRepo)(nil).Create), arg0)
}

// Exists mocks base method
func (m *MockDbRepo) Exists(arg0 types.Height) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Exists indicates an expected call of Exists
func (mr *MockDbRepoMockRecorder) Exists(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockDbRepo)(nil).Exists), arg0)
}

// GetByHeight mocks base method
func (m *MockDbRepo) GetByHeight(arg0 types.Height) ([]delegationseq.Model, errors.ApplicationError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByHeight", arg0)
	ret0, _ := ret[0].([]delegationseq.Model)
	ret1, _ := ret[1].(errors.ApplicationError)
	return ret0, ret1
}

// GetByHeight indicates an expected call of GetByHeight
func (mr *MockDbRepoMockRecorder) GetByHeight(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByHeight", reflect.TypeOf((*MockDbRepo)(nil).GetByHeight), arg0)
}

// GetCurrentByDelegatorUID mocks base method
func (m *MockDbRepo) GetCurrentByDelegatorUID(arg0 types.PublicKey) ([]delegationseq.Model, errors.ApplicationError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentByDelegatorUID", arg0)
	ret0, _ := ret[0].([]delegationseq.Model)
	ret1, _ := ret[1].(errors.ApplicationError)
	return ret0, ret1
}

// GetCurrentByDelegatorUID indicates an expected call of GetCurrentByDelegatorUID
func (mr *MockDbRepoMockRecorder) GetCurrentByDelegatorUID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentByDelegatorUID", reflect.TypeOf((*MockDbRepo)(nil).GetCurrentByDelegatorUID), arg0)
}

// GetLastByValidatorUID mocks base method
func (m *MockDbRepo) GetLastByValidatorUID(arg0 types.PublicKey) ([]delegationseq.Model, errors.ApplicationError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastByValidatorUID", arg0)
	ret0, _ := ret[0].([]delegationseq.Model)
	ret1, _ := ret[1].(errors.ApplicationError)
	return ret0, ret1
}

// GetLastByValidatorUID indicates an expected call of GetLastByValidatorUID
func (mr *MockDbRepoMockRecorder) GetLastByValidatorUID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastByValidatorUID", reflect.TypeOf((*MockDbRepo)(nil).GetLastByValidatorUID), arg0)
}
