// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/figment-networks/oasishub-indexer/repos/validatorseqrepo (interfaces: DbRepo)

// Package mock_validatorseqrepo is a generated GoMock package.
package mock_validatorseqrepo

import (
	validatorseq "github.com/figment-networks/oasishub-indexer/models/validatorseq"
	validatorseqrepo "github.com/figment-networks/oasishub-indexer/repos/validatorseqrepo"
	types "github.com/figment-networks/oasishub-indexer/types"
	errors "github.com/figment-networks/oasishub-indexer/utils/errors"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockDbRepo is a mock of DbRepo interface
type MockDbRepo struct {
	ctrl     *gomock.Controller
	recorder *MockDbRepoMockRecorder
}

// MockDbRepoMockRecorder is the mock recorder for MockDbRepo
type MockDbRepoMockRecorder struct {
	mock *MockDbRepo
}

// NewMockDbRepo creates a new mock instance
func NewMockDbRepo(ctrl *gomock.Controller) *MockDbRepo {
	mock := &MockDbRepo{ctrl: ctrl}
	mock.recorder = &MockDbRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockDbRepo) EXPECT() *MockDbRepoMockRecorder {
	return m.recorder
}

// Count mocks base method
func (m *MockDbRepo) Count() (*int64, errors.ApplicationError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count")
	ret0, _ := ret[0].(*int64)
	ret1, _ := ret[1].(errors.ApplicationError)
	return ret0, ret1
}

// Count indicates an expected call of Count
func (mr *MockDbRepoMockRecorder) Count() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockDbRepo)(nil).Count))
}

// Create mocks base method
func (m *MockDbRepo) Create(arg0 *validatorseq.Model) errors.ApplicationError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(errors.ApplicationError)
	return ret0
}

// Create indicates an expected call of Create
func (mr *MockDbRepoMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDbRepo)(nil).Create), arg0)
}

// Exists mocks base method
func (m *MockDbRepo) Exists(arg0 types.Height) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Exists indicates an expected call of Exists
func (mr *MockDbRepoMockRecorder) Exists(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockDbRepo)(nil).Exists), arg0)
}

// GetByHeight mocks base method
func (m *MockDbRepo) GetByHeight(arg0 types.Height) ([]validatorseq.Model, errors.ApplicationError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByHeight", arg0)
	ret0, _ := ret[0].([]validatorseq.Model)
	ret1, _ := ret[1].(errors.ApplicationError)
	return ret0, ret1
}

// GetByHeight indicates an expected call of GetByHeight
func (mr *MockDbRepoMockRecorder) GetByHeight(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByHeight", reflect.TypeOf((*MockDbRepo)(nil).GetByHeight), arg0)
}

// GetTotalMissedByEntityUID mocks base method
func (m *MockDbRepo) GetTotalMissedByEntityUID(arg0 types.PublicKey) (*int64, errors.ApplicationError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalMissedByEntityUID", arg0)
	ret0, _ := ret[0].(*int64)
	ret1, _ := ret[1].(errors.ApplicationError)
	return ret0, ret1
}

// GetTotalMissedByEntityUID indicates an expected call of GetTotalMissedByEntityUID
func (mr *MockDbRepoMockRecorder) GetTotalMissedByEntityUID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalMissedByEntityUID", reflect.TypeOf((*MockDbRepo)(nil).GetTotalMissedByEntityUID), arg0)
}

// GetTotalProposedByEntityUID mocks base method
func (m *MockDbRepo) GetTotalProposedByEntityUID(arg0 types.PublicKey) (*int64, errors.ApplicationError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalProposedByEntityUID", arg0)
	ret0, _ := ret[0].(*int64)
	ret1, _ := ret[1].(errors.ApplicationError)
	return ret0, ret1
}

// GetTotalProposedByEntityUID indicates an expected call of GetTotalProposedByEntityUID
func (mr *MockDbRepoMockRecorder) GetTotalProposedByEntityUID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalProposedByEntityUID", reflect.TypeOf((*MockDbRepo)(nil).GetTotalProposedByEntityUID), arg0)
}

// GetTotalSharesForInterval mocks base method
func (m *MockDbRepo) GetTotalSharesForInterval(arg0, arg1 string) ([]validatorseqrepo.Row, errors.ApplicationError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalSharesForInterval", arg0, arg1)
	ret0, _ := ret[0].([]validatorseqrepo.Row)
	ret1, _ := ret[1].(errors.ApplicationError)
	return ret0, ret1
}

// GetTotalSharesForInterval indicates an expected call of GetTotalSharesForInterval
func (mr *MockDbRepoMockRecorder) GetTotalSharesForInterval(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalSharesForInterval", reflect.TypeOf((*MockDbRepo)(nil).GetTotalSharesForInterval), arg0, arg1)
}

// GetTotalValidatedByEntityUID mocks base method
func (m *MockDbRepo) GetTotalValidatedByEntityUID(arg0 types.PublicKey) (*int64, errors.ApplicationError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalValidatedByEntityUID", arg0)
	ret0, _ := ret[0].(*int64)
	ret1, _ := ret[1].(errors.ApplicationError)
	return ret0, ret1
}

// GetTotalValidatedByEntityUID indicates an expected call of GetTotalValidatedByEntityUID
func (mr *MockDbRepoMockRecorder) GetTotalValidatedByEntityUID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalValidatedByEntityUID", reflect.TypeOf((*MockDbRepo)(nil).GetTotalValidatedByEntityUID), arg0)
}

// GetValidatorSharesForInterval mocks base method
func (m *MockDbRepo) GetValidatorSharesForInterval(arg0 types.PublicKey, arg1, arg2 string) ([]validatorseqrepo.Row, errors.ApplicationError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValidatorSharesForInterval", arg0, arg1, arg2)
	ret0, _ := ret[0].([]validatorseqrepo.Row)
	ret1, _ := ret[1].(errors.ApplicationError)
	return ret0, ret1
}

// GetValidatorSharesForInterval indicates an expected call of GetValidatorSharesForInterval
func (mr *MockDbRepoMockRecorder) GetValidatorSharesForInterval(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValidatorSharesForInterval", reflect.TypeOf((*MockDbRepo)(nil).GetValidatorSharesForInterval), arg0, arg1, arg2)
}

// Save mocks base method
func (m *MockDbRepo) Save(arg0 *validatorseq.Model) errors.ApplicationError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0)
	ret0, _ := ret[0].(errors.ApplicationError)
	return ret0
}

// Save indicates an expected call of Save
func (mr *MockDbRepoMockRecorder) Save(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockDbRepo)(nil).Save), arg0)
}
