// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/figment-networks/oasishub-indexer/client (interfaces: AccountClient,BlockClient,ChainClient,EventClient,StateClient,TransactionClient,ValidatorClient)

// Package mock_client is a generated GoMock package.
package mock_client

import (
	accountpb "github.com/figment-networks/oasis-rpc-proxy/grpc/account/accountpb"
	blockpb "github.com/figment-networks/oasis-rpc-proxy/grpc/block/blockpb"
	chainpb "github.com/figment-networks/oasis-rpc-proxy/grpc/chain/chainpb"
	eventpb "github.com/figment-networks/oasis-rpc-proxy/grpc/event/eventpb"
	statepb "github.com/figment-networks/oasis-rpc-proxy/grpc/state/statepb"
	transactionpb "github.com/figment-networks/oasis-rpc-proxy/grpc/transaction/transactionpb"
	validatorpb "github.com/figment-networks/oasis-rpc-proxy/grpc/validator/validatorpb"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockAccountClient is a mock of AccountClient interface
type MockAccountClient struct {
	ctrl     *gomock.Controller
	recorder *MockAccountClientMockRecorder
}

// MockAccountClientMockRecorder is the mock recorder for MockAccountClient
type MockAccountClientMockRecorder struct {
	mock *MockAccountClient
}

// NewMockAccountClient creates a new mock instance
func NewMockAccountClient(ctrl *gomock.Controller) *MockAccountClient {
	mock := &MockAccountClient{ctrl: ctrl}
	mock.recorder = &MockAccountClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockAccountClient) EXPECT() *MockAccountClientMockRecorder {
	return m.recorder
}

// GetByAddress mocks base method
func (m *MockAccountClient) GetByAddress(arg0 string, arg1 int64) (*accountpb.GetByAddressResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByAddress", arg0, arg1)
	ret0, _ := ret[0].(*accountpb.GetByAddressResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByAddress indicates an expected call of GetByAddress
func (mr *MockAccountClientMockRecorder) GetByAddress(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByAddress", reflect.TypeOf((*MockAccountClient)(nil).GetByAddress), arg0, arg1)
}

// MockBlockClient is a mock of BlockClient interface
type MockBlockClient struct {
	ctrl     *gomock.Controller
	recorder *MockBlockClientMockRecorder
}

// MockBlockClientMockRecorder is the mock recorder for MockBlockClient
type MockBlockClientMockRecorder struct {
	mock *MockBlockClient
}

// NewMockBlockClient creates a new mock instance
func NewMockBlockClient(ctrl *gomock.Controller) *MockBlockClient {
	mock := &MockBlockClient{ctrl: ctrl}
	mock.recorder = &MockBlockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockBlockClient) EXPECT() *MockBlockClientMockRecorder {
	return m.recorder
}

// GetByHeight mocks base method
func (m *MockBlockClient) GetByHeight(arg0 int64) (*blockpb.GetByHeightResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByHeight", arg0)
	ret0, _ := ret[0].(*blockpb.GetByHeightResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByHeight indicates an expected call of GetByHeight
func (mr *MockBlockClientMockRecorder) GetByHeight(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByHeight", reflect.TypeOf((*MockBlockClient)(nil).GetByHeight), arg0)
}

// MockChainClient is a mock of ChainClient interface
type MockChainClient struct {
	ctrl     *gomock.Controller
	recorder *MockChainClientMockRecorder
}

// MockChainClientMockRecorder is the mock recorder for MockChainClient
type MockChainClientMockRecorder struct {
	mock *MockChainClient
}

// NewMockChainClient creates a new mock instance
func NewMockChainClient(ctrl *gomock.Controller) *MockChainClient {
	mock := &MockChainClient{ctrl: ctrl}
	mock.recorder = &MockChainClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockChainClient) EXPECT() *MockChainClientMockRecorder {
	return m.recorder
}

// GetConstants mocks base method
func (m *MockChainClient) GetConstants() (*chainpb.GetConstantsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConstants")
	ret0, _ := ret[0].(*chainpb.GetConstantsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConstants indicates an expected call of GetConstants
func (mr *MockChainClientMockRecorder) GetConstants() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConstants", reflect.TypeOf((*MockChainClient)(nil).GetConstants))
}

// GetHead mocks base method
func (m *MockChainClient) GetHead() (*chainpb.GetHeadResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHead")
	ret0, _ := ret[0].(*chainpb.GetHeadResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHead indicates an expected call of GetHead
func (mr *MockChainClientMockRecorder) GetHead() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHead", reflect.TypeOf((*MockChainClient)(nil).GetHead))
}

// GetMetaByHeight mocks base method
func (m *MockChainClient) GetMetaByHeight(arg0 int64) (*chainpb.GetMetaByHeightResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetaByHeight", arg0)
	ret0, _ := ret[0].(*chainpb.GetMetaByHeightResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetaByHeight indicates an expected call of GetMetaByHeight
func (mr *MockChainClientMockRecorder) GetMetaByHeight(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetaByHeight", reflect.TypeOf((*MockChainClient)(nil).GetMetaByHeight), arg0)
}

// GetStatus mocks base method
func (m *MockChainClient) GetStatus() (*chainpb.GetStatusResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatus")
	ret0, _ := ret[0].(*chainpb.GetStatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatus indicates an expected call of GetStatus
func (mr *MockChainClientMockRecorder) GetStatus() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatus", reflect.TypeOf((*MockChainClient)(nil).GetStatus))
}

// MockEventClient is a mock of EventClient interface
type MockEventClient struct {
	ctrl     *gomock.Controller
	recorder *MockEventClientMockRecorder
}

// MockEventClientMockRecorder is the mock recorder for MockEventClient
type MockEventClientMockRecorder struct {
	mock *MockEventClient
}

// NewMockEventClient creates a new mock instance
func NewMockEventClient(ctrl *gomock.Controller) *MockEventClient {
	mock := &MockEventClient{ctrl: ctrl}
	mock.recorder = &MockEventClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockEventClient) EXPECT() *MockEventClientMockRecorder {
	return m.recorder
}

// GetEscrowEventsByHeight mocks base method
func (m *MockEventClient) GetEscrowEventsByHeight(arg0 int64) (*eventpb.GetEscrowEventsByHeightResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEscrowEventsByHeight", arg0)
	ret0, _ := ret[0].(*eventpb.GetEscrowEventsByHeightResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEscrowEventsByHeight indicates an expected call of GetEscrowEventsByHeight
func (mr *MockEventClientMockRecorder) GetEscrowEventsByHeight(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEscrowEventsByHeight", reflect.TypeOf((*MockEventClient)(nil).GetEscrowEventsByHeight), arg0)
}

// MockStateClient is a mock of StateClient interface
type MockStateClient struct {
	ctrl     *gomock.Controller
	recorder *MockStateClientMockRecorder
}

// MockStateClientMockRecorder is the mock recorder for MockStateClient
type MockStateClientMockRecorder struct {
	mock *MockStateClient
}

// NewMockStateClient creates a new mock instance
func NewMockStateClient(ctrl *gomock.Controller) *MockStateClient {
	mock := &MockStateClient{ctrl: ctrl}
	mock.recorder = &MockStateClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockStateClient) EXPECT() *MockStateClientMockRecorder {
	return m.recorder
}

// GetByHeight mocks base method
func (m *MockStateClient) GetByHeight(arg0 int64) (*statepb.GetByHeightResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByHeight", arg0)
	ret0, _ := ret[0].(*statepb.GetByHeightResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByHeight indicates an expected call of GetByHeight
func (mr *MockStateClientMockRecorder) GetByHeight(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByHeight", reflect.TypeOf((*MockStateClient)(nil).GetByHeight), arg0)
}

// GetStakingByHeight mocks base method
func (m *MockStateClient) GetStakingByHeight(arg0 int64) (*statepb.GetStakingByHeightResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStakingByHeight", arg0)
	ret0, _ := ret[0].(*statepb.GetStakingByHeightResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStakingByHeight indicates an expected call of GetStakingByHeight
func (mr *MockStateClientMockRecorder) GetStakingByHeight(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStakingByHeight", reflect.TypeOf((*MockStateClient)(nil).GetStakingByHeight), arg0)
}

// MockTransactionClient is a mock of TransactionClient interface
type MockTransactionClient struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionClientMockRecorder
}

// MockTransactionClientMockRecorder is the mock recorder for MockTransactionClient
type MockTransactionClientMockRecorder struct {
	mock *MockTransactionClient
}

// NewMockTransactionClient creates a new mock instance
func NewMockTransactionClient(ctrl *gomock.Controller) *MockTransactionClient {
	mock := &MockTransactionClient{ctrl: ctrl}
	mock.recorder = &MockTransactionClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockTransactionClient) EXPECT() *MockTransactionClientMockRecorder {
	return m.recorder
}

// GetByHeight mocks base method
func (m *MockTransactionClient) GetByHeight(arg0 int64) (*transactionpb.GetByHeightResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByHeight", arg0)
	ret0, _ := ret[0].(*transactionpb.GetByHeightResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByHeight indicates an expected call of GetByHeight
func (mr *MockTransactionClientMockRecorder) GetByHeight(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByHeight", reflect.TypeOf((*MockTransactionClient)(nil).GetByHeight), arg0)
}

// MockValidatorClient is a mock of ValidatorClient interface
type MockValidatorClient struct {
	ctrl     *gomock.Controller
	recorder *MockValidatorClientMockRecorder
}

// MockValidatorClientMockRecorder is the mock recorder for MockValidatorClient
type MockValidatorClientMockRecorder struct {
	mock *MockValidatorClient
}

// NewMockValidatorClient creates a new mock instance
func NewMockValidatorClient(ctrl *gomock.Controller) *MockValidatorClient {
	mock := &MockValidatorClient{ctrl: ctrl}
	mock.recorder = &MockValidatorClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockValidatorClient) EXPECT() *MockValidatorClientMockRecorder {
	return m.recorder
}

// GetByHeight mocks base method
func (m *MockValidatorClient) GetByHeight(arg0 int64) (*validatorpb.GetByHeightResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByHeight", arg0)
	ret0, _ := ret[0].(*validatorpb.GetByHeightResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByHeight indicates an expected call of GetByHeight
func (mr *MockValidatorClientMockRecorder) GetByHeight(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByHeight", reflect.TypeOf((*MockValidatorClient)(nil).GetByHeight), arg0)
}
