// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/figment-networks/oasishub-indexer/repos/syncablerepo (interfaces: ProxyRepo)

// Package mock_syncablerepo is a generated GoMock package.
package mock_syncablerepo

import (
	syncable "github.com/figment-networks/oasishub-indexer/models/syncable"
	types "github.com/figment-networks/oasishub-indexer/types"
	errors "github.com/figment-networks/oasishub-indexer/utils/errors"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockProxyRepo is a mock of ProxyRepo interface
type MockProxyRepo struct {
	ctrl     *gomock.Controller
	recorder *MockProxyRepoMockRecorder
}

// MockProxyRepoMockRecorder is the mock recorder for MockProxyRepo
type MockProxyRepoMockRecorder struct {
	mock *MockProxyRepo
}

// NewMockProxyRepo creates a new mock instance
func NewMockProxyRepo(ctrl *gomock.Controller) *MockProxyRepo {
	mock := &MockProxyRepo{ctrl: ctrl}
	mock.recorder = &MockProxyRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockProxyRepo) EXPECT() *MockProxyRepoMockRecorder {
	return m.recorder
}

// GetByHeight mocks base method
func (m *MockProxyRepo) GetByHeight(arg0 syncable.Type, arg1 types.Height) (*syncable.Model, errors.ApplicationError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByHeight", arg0, arg1)
	ret0, _ := ret[0].(*syncable.Model)
	ret1, _ := ret[1].(errors.ApplicationError)
	return ret0, ret1
}

// GetByHeight indicates an expected call of GetByHeight
func (mr *MockProxyRepoMockRecorder) GetByHeight(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByHeight", reflect.TypeOf((*MockProxyRepo)(nil).GetByHeight), arg0, arg1)
}

// GetHead mocks base method
func (m *MockProxyRepo) GetHead() (*syncable.Model, errors.ApplicationError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHead")
	ret0, _ := ret[0].(*syncable.Model)
	ret1, _ := ret[1].(errors.ApplicationError)
	return ret0, ret1
}

// GetHead indicates an expected call of GetHead
func (mr *MockProxyRepoMockRecorder) GetHead() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHead", reflect.TypeOf((*MockProxyRepo)(nil).GetHead))
}
